chore: format with shfmt

diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -2,36 +2,36 @@
 # cSpell:words elif
 
 if [ "$1" = "-h" ] || [ "$1" == "--help" ]; then
-    printf "\n"
-    printf "\033[1m  t - the smart tmux session manager\033[0m\n"
-    printf "\033[37m  https://github.com/joshmedeski/t-smart-tmux-session-manager\n"
-    printf "\n"
-    printf "\033[32m  Run interactive mode\n"
-    printf "\033[34m      t\n"
-    printf "\n"
-    printf "\033[32m  Go to session\n"
-    printf "\033[34m      t {name}\n"
-    printf "\n"
-    printf "\033[32m  Open popup (while in tmux)\n"
-    printf "\033[34m      <prefix>+T\n"
-    printf "\n"
-    printf "\033[32m  Show help\n"
-    printf "\033[34m      t -h\n"
-    printf "\033[34m      t --help\n"
-    printf "\n"
+	printf "\n"
+	printf "\033[1m  t - the smart tmux session manager\033[0m\n"
+	printf "\033[37m  https://github.com/joshmedeski/t-smart-tmux-session-manager\n"
+	printf "\n"
+	printf "\033[32m  Run interactive mode\n"
+	printf "\033[34m      t\n"
+	printf "\n"
+	printf "\033[32m  Go to session\n"
+	printf "\033[34m      t {name}\n"
+	printf "\n"
+	printf "\033[32m  Open popup (while in tmux)\n"
+	printf "\033[34m      <prefix>+T\n"
+	printf "\n"
+	printf "\033[32m  Show help\n"
+	printf "\033[34m      t -h\n"
+	printf "\033[34m      t --help\n"
+	printf "\n"
 elif [ $# -eq 0 ]; then
-    FZF_BORDER_LABEL=" t - smart tmux session manager "
-    if [ "$TMUX" = "" ]; then
-        ZOXIDE_RESULT=$(zoxide query -l | fzf --reverse --border-label "$FZF_BORDER_LABEL")
-    else
-        ZOXIDE_RESULT=$(zoxide query -l | fzf-tmux -p --reverse --border-label "$FZF_BORDER_LABEL")
-    fi
+	FZF_BORDER_LABEL=" t - smart tmux session manager "
+	if [ "$TMUX" = "" ]; then
+		ZOXIDE_RESULT=$(zoxide query -l | fzf --reverse --border-label "$FZF_BORDER_LABEL")
+	else
+		ZOXIDE_RESULT=$(zoxide query -l | fzf-tmux -p --reverse --border-label "$FZF_BORDER_LABEL")
+	fi
 else
-    ZOXIDE_RESULT=$(zoxide query "$1")
+	ZOXIDE_RESULT=$(zoxide query "$1")
 fi
 
 if [ "$ZOXIDE_RESULT" = "" ]; then
-    exit # exit silently if no result
+	exit # exit silently if no result
 fi
 
 FOLDER=$(basename "$ZOXIDE_RESULT")
@@ -39,19 +39,19 @@ SESSION_NAME=$(echo "$FOLDER" | tr ' ' '_' | tr '.' '_' | tr ':' '_')
 
 SESSION=$(tmux list-sessions -F '#S' | grep "^$SESSION_NAME$") # find existing session
 
-if [ "$TMUX" = "" ]; then # if not currently in tmux
-    if [ "$SESSION" = "" ]; then # session does not exist
-        cd "$ZOXIDE_RESULT" || exit 1 # jump to directory
-        tmux new-session -s "$SESSION_NAME" # create session and attach
-    else # session exists
-        tmux attach -t "$SESSION" # attach to session
-    fi
-else # currently in tmux
-    if [ "$SESSION" = "" ]; then # session does not exist
-        cd "$ZOXIDE_RESULT" || exit 1 # jump to directory
-        tmux new-session -d -s "$SESSION_NAME" # create session
-        tmux switch-client -t "$SESSION_NAME" # attach to session
-    else # session exists
-        tmux switch-client -t "$SESSION" # switch to session
-    fi
+if [ "$TMUX" = "" ]; then             # if not currently in tmux
+	if [ "$SESSION" = "" ]; then         # session does not exist
+		cd "$ZOXIDE_RESULT" || exit 1       # jump to directory
+		tmux new-session -s "$SESSION_NAME" # create session and attach
+	else                                 # session exists
+		tmux attach -t "$SESSION"           # attach to session
+	fi
+else                                     # currently in tmux
+	if [ "$SESSION" = "" ]; then            # session does not exist
+		cd "$ZOXIDE_RESULT" || exit 1          # jump to directory
+		tmux new-session -d -s "$SESSION_NAME" # create session
+		tmux switch-client -t "$SESSION_NAME"  # attach to session
+	else                                    # session exists
+		tmux switch-client -t "$SESSION"       # switch to session
+	fi
 fi
